// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Curry             from "bs-platform/lib/es6/curry.js";
import * as React             from "react";
import * as ReasonReact       from "reason-react/lib/es6/src/ReasonReact.js";
import * as JoejoeCapybaraJpg from "../../../src/joejoe-capybara.jpg";

var component = ReasonReact.statelessComponent("App");

((require('../../../src/App.scss')));

function handleClick(_, _$1) {
  console.log("hey buddy!");
  return /* () */0;
}

function make(message, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  className: "app"
                }, React.createElement("div", {
                      className: "appContainer"
                    }, React.createElement("h1", {
                          className: "appHeader"
                        }, "Hey Buddy"), React.createElement("img", {
                          className: "App-capy",
                          alt: "capybara",
                          src: JoejoeCapybaraJpg
                        }), React.createElement("div", {
                          className: "appButton",
                          onClick: Curry._1(self[/* handle */0], handleClick)
                        }, message)));
    });
  return newrecord;
}

export {
  component   ,
  handleClick ,
  make        ,
  
}
/* component Not a pure module */
