// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as JoejoeCapybaraJpg from "./joejoe-capybara.jpg";

var component = ReasonReact.statelessComponent("App");

((require('./app.scss')));

function handleClick(_, _$1) {
  console.log("hey buddy!");
  return /* () */0;
}

function make(message, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  className: "app"
                }, React.createElement("div", {
                      className: "appContainer"
                    }, React.createElement("h1", {
                          className: "appHeader"
                        }, "Hey Buddy"), React.createElement("div", {
                          className: "buddyBox"
                        }, React.createElement("img", {
                              className: "App-capy",
                              alt: "capybara",
                              src: JoejoeCapybaraJpg
                            }), React.createElement("div", {
                              className: "appButton",
                              onClick: Curry._1(self[/* handle */0], handleClick)
                            }, message))));
    });
  return newrecord;
}

export {
  component ,
  handleClick ,
  make ,
  
}
/* component Not a pure module */
