// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ReactDOMRe        from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact       from "reason-react/src/ReasonReact.js";
import * as App$ReactTemplate from "./app.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$ReactTemplate.make("Click me!", /* array */[])), "root");

export {
  
}
/*  Not a pure module */
